### ISSUE TITLE
不会添加文件啊

### ISSUE THREAD

**Issue by ming1259** [Mohism-Research/Big_Data_Inc#1]
还不会手机端添加文件啊

**Comment by JelloHuang** [comment]
用公司电脑,怎么不用公司电脑?

**Comment by mohismtaoism** [comment]
https://help.github.com/articles/fork-a-repo/

https://github.com/Mohism-Research/Super-Taoism-Archives/blob/master/bannercamp/GIT-for-dummy.md

**Comment by mohismtaoism** [comment]
it should be closed.
