### ISSUE TITLE
進一步完善爬蟲功能

### ISSUE THREAD

**Issue by JelloHuang** [Mohism-Research/Big_Data_Inc#11]
１　weixinq網站　所有的二維碼　分類出來
２　按時間取出出來，之前很久的群自動加不了，所以就不要了，按時間屬性(要麼取前幾頁就行)
３　按那個視頻，設計一個最最最簡單的(不要再像以前那樣子貪求多與完善了)windows上可以自動加群的
windows version 軟件，越簡單越好，以後再完善！！！！！切記，以簡單為美．

**Comment by JelloHuang** [comment]
http://codingpy.com/article/scrapy-01-meizitu/ 

如果你不想自己重新运行一遍爬虫，可以考虑在微信公众号的后台回复“mzt”，会有惊喜。

参考资料

http://toutiao.com/a6300929522393841921/ 
http://mazih.com/post/cibuwb7bu0000rfa2m169vzv9/

**Comment by JelloHuang** [comment]
已經實現第三條

**Comment by JelloHuang** [comment]
明天用了幾個小時基本實現3

**Comment by JelloHuang** [comment]
@ming1259 1 與2 兩步你把他實現了,目前已經沒大有事處理,先做好自己的本職工作,加強鍛鍊與進一步實踐完善

**Comment by ming1259** [comment]
1.提取分类属性，本来后台就取到了分类信息，不知道怎么处理分类信息？
2.我就附加条件，只能下载有效期内的二维码即可，失效的直接不让下载即可

**Comment by ming1259** [comment]
如果有gui的话，会按照命令预先提取所有分类显示在下拉列表，然后按照用户选择的分类再去过滤采集数据，原先代码就已经可以取到分类数据了，回头我再想下怎么修改代码
