### ISSUE TITLE
setup wiki and like mantis

### ISSUE THREAD

**Issue by JelloHuang** [Mohism-Research/Big_Data_Inc#24]
setup wiki and like mantis
不是mantis的bug系統,是一種可以check到工作進展程度的東西
schedule: 5.4

**Comment by mohismtaoism** [comment]
Why not using github's issue tracker and wiki? For confidential issue?

**Comment by JelloHuang** [comment]
yes - confidential .we need to find some geneius for us

**Comment by JelloHuang** [comment]
but we also have some thing to private

**Comment by mohismtaoism** [comment]
Trac has been established Now!
