### ISSUE TITLE
pls init the “How the Steel Was Tempered”

### ISSUE THREAD

**Issue by JelloHuang** [Mohism-Research/Big_Data_Inc#4]
Schedule : 3.15.
pls finish today ,we have talk at this morning。thx
and send to me and i will review.

**Comment by mohismtaoism** [comment]
You mean I need to create a new repo named by "Steel Plan" or just one document??

**Comment by mohismtaoism** [comment]
https://github.com/Mohism-Research/Super-Taoism-Archives/blob/master/bannercamp/Mohism_Staffs_newbie_guide.md
