### ISSUE TITLE
pls add more detail  “How the Steel Was Tempered

### ISSUE THREAD

**Issue by JelloHuang** [Mohism-Research/Big_Data_Inc#5]
https://github.com/Mohism-Research/Super-Taoism-Archives/blob/master/bannercamp/Mohism_Staffs_newbie_guide.md
2. Technical issues need to detail step which how to make it

**Comment by JelloHuang** [comment]
schedule:3.20

**Comment by mohismtaoism** [comment]
I have finished the technical issue in this tutorial. This issue should be shut down.
