### ISSUE TITLE
pls setup git server in our server

### ISSUE THREAD

**Issue by JelloHuang** [Mohism-Research/Big_Data_Inc#7]
we need to setup private server in our server .
so pls help to make it,thx
BTW:the ip address and how to build u can ask alex
schedule: 4.1

**Comment by JelloHuang** [comment]
u can ref : https://github.com/Mohism-Research/Super-Taoism-Archives/blob/master/bannercamp/Mohism_Staffs_newbie_guide.md

**Comment by JelloHuang** [comment]
suspend

**Comment by JelloHuang** [comment]
open and pls help to build like github issue function on our server,thx

**Comment by JelloHuang** [comment]
這個會block選擇的招人plan,so pls do it more quickly,thx.
and then all git code need to push git server in private.
and also set right

**Comment by mohismtaoism** [comment]
Done.

**Comment by mohismtaoism** [comment]
Done
